server:
  port: 8077

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  data:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      repositories:
        bootstrap-mode: default
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: reader-ates-auth
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      "[schema.registry.url]": http://localhost:9095
      "[auto.register.schemas]": true